### PR TITLE
Groovy implementation using Jetty and GSP

### PR DESCRIPTION
**Pull request by rlovtangen**

### CODE REVIEW

**Comment by bodil** [comment]
Are you sure putting the logic inside a GSP is a good idea? If that feels natural to you, I'll merge this - just want to be sure this is really idiomatic Groovy. If somebody tried this with JSPs, I'd tell them to reconsider for their own good...

**Comment by rlovtangen** [comment]
Well, there is no controller involved here, as these extreme startup servers are 'simplest thing that could possibly work'. In a real project I would of course separate controller and view, and move the logic away from the controller, but none of the extreme startup servers do that.
Anyhow, the Groovlets example is probably much better to keep, so you can discard this pull request. With Kjetils two examples as well, there are more than enough Groovy examples.

**Comment by bodil** [comment]
OK. The thing is, it gets real very quickly once the competition progresses, and I can see this code getting really messy in a hurry. As opposed to the Groovlets code - one line of code for the initial state is sweet. :)

**Comment by rlovtangen** [comment]
Yes, it can get messy. Been a contender once :)
You can of course create functions, so the mess would be on the same level as the other examples.

**Pull request closed without merging**
